version: '3'
services:
  redis:
    image: 'redis:alpine'
    command: redis-server --requirepass password
    expose:
      - '6379'
    volumes:
      - ./.cache/redis:/data
    ports:
      - '6379:6379'
  database:
    image: 'postgres:13'
    environment:
      - POSTGRES_USER=ilher
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ilher_dev_db
    ports:
      - '5432:5432'
